### ISSUE TITLE
[FEATURE][GENERAL] Standardize response messages

### ISSUE THREAD

**Issue by adrianshiokawa** [tq1/node-push-sender#18]
Response messages should adopt a standard, foi easier treatment for module's users
Currently, the responses are:

Apn sender:

```
{
device: 
success:
errorCode:
}
```

GCM sender:

```
{
message_id:
error:
}
```

This issue relates to #17, which has response message considerations 
## Tasks
- [ ] Define a standard for node pusher responses
- [ ] Return this standard response for GCM
- [ ] Return this standard response for APN
- [ ] Tests
## Definition of Done
- [ ] Responses returned should follow the same standard for both GCM and APN
