### ISSUE TITLE
[FEATURE][GENERAL] Configure authorization only once

### ISSUE THREAD

**Issue by adrianshiokawa** [tq1/node-push-sender#19]
Node push sender should need the `authorization` parameters only once, and get consumed only with push relevant parameters (tokens, etc...)
## Tasks
- [ ] Initialize module with auth parameters
- [ ] Auth parameters for GCM
- [ ] Auth parameters for APN
- [ ] Successfully push after node push sender setup
- [ ] Tests
## Definition of Done
- [ ] Module can be used without authorization params, after it's initialization
