### ISSUE TITLE
[CHORE] Create example usages

### ISSUE THREAD

**Issue by askmon** [tq1/node-push-sender#8]
## Tasks Checklist
- [ ] Add GCM usage example
- [ ] Add APNS usage example
- [ ] Add considerations about auth fields to docs
- [ ] Add configuration steps to docs
